### ISSUE TITLE
Including with/from in GO annotation

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#10]
The with/from part in the GO annotation is missing. In the GAF file, the with/from annotation is shown in column 8. For more information on column 8, please see the following link:
http://www.geneontology.org/page/go-annotation-file-gaf-format-21

In PlasmoDB the with/from part is shown as Support for Evidence Code assignment. Here is an example:
http://plasmodb.org/plasmo/app/record/gene/PF3D7_1207300#GOTerms
 
The with/from annotation can either be a UniProt link, a GeneDB link, InterPro ID, Pfam ID or a link to TMHMM. 
Here is an example for TMHMM. 
http://www.genedb.org/gene/PF3D7_0721500
![screen shot 2019-01-07 at 07 50 42](https://user-images.githubusercontent.com/25098772/50755455-f9414a00-1250-11e9-8bfe-85ef762231c8.png)

**Comment by magnusmanske** [comment]
These should all be working in dev now, example: https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_0721500
Items will be updated with the next run.

**Comment by uliboehme** [comment]
HI Magnus, 

Thanks for looking into this. I can see the link to TMHMM for your example. Thanks!

Should the with/from also show up on other genes on genedb-dev? I cannot see it for example for RH5. This gene binds to various other proteins, those gene IDs should show up in the with/from column. You can see the with/from on PlasmoDB (it is listed as support for evidence code assignment). 
http://plasmodb.org/plasmo/app/record/gene/PF3D7_0424100#GOTerms

I don’t see this on genedb-dev. 
https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_0424100

Would be great if you could let me know if I’m looking in the wrong place. 

Thanks, 
Uli


> On 27 Feb 2019, at 10:56, Magnus Manske <notifications@github.com> wrote:
> 
> These should all be working in dev now, example: https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_0721500 <https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_0721500>
> Items will be updated with the next run.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magnusmanske_genedb-5Fwd_issues_10-23issuecomment-2D467817923&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=o80MgTKNyJNlOZHuLZoXVoXK6oAPwGMyDB-bTvXigWs&s=-8ChmGFQ5eYb920u_ZlRSAXl-7nQ1Sh0BnxDn7Qr3hc&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX76FJ7OiA3LFwNMG-5FAoBLJ77TIdoiWuks5vRmRmgaJpZM4ZID5j&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=o80MgTKNyJNlOZHuLZoXVoXK6oAPwGMyDB-bTvXigWs&s=JslePWVwmAkyBUZhBvlpav1J4LSv812mNsqGELXj8vg&e=>.
> 




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
