### ISSUE TITLE
Product evidence codes

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#11]
Similar to GO annotation, product evidence codes are assigned. They are shown in the GFF file. 

Example:
http://www.genedb.org/gene/PF3D7_1207300
![screen shot 2019-01-07 at 07 44 20](https://user-images.githubusercontent.com/25098772/50755160-16c1e400-1250-11e9-82f5-c62d33ee4271.png)

This is how it looks in the GFF file:
product=term%3DLIMP protein%2C putative%3Bdb_xref%3DPMID:28525314%3Bwith%3DGeneDB:PBANKA_0605800%3Bevidence%3DInferred from Sequence Orthology

These products evidence codes are not shown in PlasmoDB. GeneDB is currently the only place where the community can view them. Therefore it would be great to also show them on the new site.

**Comment by magnusmanske** [comment]
Should be live: https://www.genedb.org/#/gene/PF3D7_1207300

**Comment by uliboehme** [comment]
Hi Magnus, 

Sorry, I’ve cleared my cache but still cannot see the product evidence code for LIMP protein. Not sure if I’m looking in the wrong place. 

Thanks, 
Uli

> On 26 Feb 2019, at 13:55, Magnus Manske <notifications@github.com> wrote:
> 
> Should be live: https://www.genedb.org/#/gene/PF3D7_1207300 <https://www.genedb.org/#/gene/PF3D7_1207300>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magnusmanske_genedb-5Fwd_issues_11-23issuecomment-2D467447029&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=BttpGWiq2xYRc7vWd-j9wYs43Umc_6WJ0fUhNXionVw&s=N6gbjt5ydDP13ytsq9y1aXkv7iAZZoTY6DSdGOfuy_0&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX76FFKdG-2DHgXYFAJgGXMzHJiD6lU8ejks5vRTzkgaJpZM4ZIFZC&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=BttpGWiq2xYRc7vWd-j9wYs43Umc_6WJ0fUhNXionVw&s=lcBom-e4RkoIU5ufh3TnuSSOevHt0sVnatIwkuaYu44&e=>.
> 




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by magnusmanske** [comment]
Is this correct?
![screen shot 2019-02-26 at 15 30 50](https://user-images.githubusercontent.com/1406572/53424708-94e27180-39db-11e9-8a36-4b38667ecd34.png)

**Comment by uliboehme** [comment]
The product is correct. However it would be nice to show the evidence for the product as well. This is how it is shown in the GFF file. 

product=term%3DLIMP protein%2C putative%3Bdb_xref%3DPMID:28525314%3Bwith%3DGeneDB:PBANKA_0605800%3Bevidence%3DInferred from Sequence Orthology;

The evidence code is ISO, the reference PMID:28525314 and the support for evidence code assignment is GeneDB:PBANKA_0605800

FungiDB has started including this in a table (currently only on the qa site). Is there a possibility to show something similar on Wikidata?




> On 26 Feb 2019, at 15:31, Magnus Manske <notifications@github.com> wrote:
> 
> Is this correct?
>  <https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_1406572_53424708-2D94e27180-2D39db-2D11e9-2D8a36-2D4b38667ecd34.png&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=scsF40D068ncMM58BjZQHSUtIsjv0sFiRW86xbPUzto&s=geBO9w5TGNoXYVZTPNVMfMxLcKc2zhZ21zlzlNmzsgM&e=>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_magnusmanske_genedb-5Fwd_issues_11-23issuecomment-2D467484717&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=scsF40D068ncMM58BjZQHSUtIsjv0sFiRW86xbPUzto&s=auNzQNxMPyJ4-QXKZEl-UyWqAq15Df3wVUTk0CfVBZk&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AX76FEWgQXdp1faI0QbNHP5ZOFoHHB27ks5vRVNjgaJpZM4ZIFZC&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=af4zXwQtKNLvVIiDVaurRw&m=scsF40D068ncMM58BjZQHSUtIsjv0sFiRW86xbPUzto&s=CtiMpUEj1bJSmdGlUoiBwZAxySz_9TxnkOQ66zaSFGQ&e=>.
> 




-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
