### ISSUE TITLE
Including NOT qualifier in Gene Ontology

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#12]
Column 4 of the GAF file sometimes has a NOT qualifier. NOT is used to make an explicit note that the gene product is not associated with the GO term.

This is currently not shown on the new site. 

Here is an example:
http://plasmodb.org/plasmo/app/record/gene/PF3D7_1011900#GOTerms

**Comment by magnusmanske** [comment]
Now showing, example: https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_1011900
Items will be updated on the next run
