### ISSUE TITLE
GeneDB is shown as source for GO terms with IEA evidence code. It should be InterPro. 

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#13]
On a regular basis InterPro is being run in Chado. Based on InterPro domains GO terms are automatically assigned with the evidence code IEA .(http://wiki.geneontology.org/index.php/Inferred_from_Electronic_Annotation_(IEA))

IEA evidence codes should be linked to InterPro. Currently GeneDB is shown as source for these GO terms. The InterPro link is present in column 8 of the GAF file. 

Here is an example with two GO terms with IEA evidence codes. 
https://tools.wmflabs.org/genedb/#/gene/PF3D7_0810800

This is how it is currently shown in GeneDB:
![screen shot 2019-01-07 at 08 05 50](https://user-images.githubusercontent.com/25098772/50756130-1414be00-1253-11e9-8713-0992446daaa5.png)
http://www.genedb.org/gene/PF3D7_0810800

**Comment by magnusmanske** [comment]
Works now, example: https://www.genedb.org/#/gene/PF3D7_0810800
Items will be updated with the next run
