### ISSUE TITLE
Products and GO terms that have been deleted or replaced in chado with a new term should be overwritten. 

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#14]
Products and GO terms that have been deleted or replaced in chado with a new term should be overwritten. 

Here is an example:
Based on a recent publication, the product "conserved Plasmodium protein, unknown function" has been replaced with "ATP synthase-associated protein, putative" 
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1142800

**Comment by magnusmanske** [comment]
Done.
