### ISSUE TITLE
Gene name is shown in previously known as section

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#16]
Genes that were newly added in the last few years (and were probably not present when 3D7 was originally loaded into Wikidata) show the gene name in the previously known as section. This is also the case for all new genomes that were recently loaded into Wikidata. 

Here are a few examples:
http://www.genedb.org/gene/PF3D7_0530750
![screen shot 2019-01-07 at 07 55 43](https://user-images.githubusercontent.com/25098772/50755669-a74cf400-1251-11e9-91c9-c50342ba64fe.png)
https://tools.wmflabs.org/genedb/#/gene/PF3D7_0530750

http://www.genedb.org/gene/PF3D7_0808450
![screen shot 2019-01-07 at 07 56 39](https://user-images.githubusercontent.com/25098772/50755716-c9df0d00-1251-11e9-823f-3903c8132280.png)
https://tools.wmflabs.org/genedb/#/gene/PF3D7_0808450

http://www.genedb.org/gene/PBANKA_1410950
![screen shot 2019-01-07 at 07 57 22](https://user-images.githubusercontent.com/25098772/50755743-df543700-1251-11e9-80f1-27ddb54a12eb.png)
https://tools.wmflabs.org/genedb/#/search/PBANKA_1410950

Gene name in this case should be AMA1. 
https://tools.wmflabs.org/genedb/#/gene/PVP01_0934200

**Comment by magnusmanske** [comment]
Display was changed, value swill change with the next update
