### ISSUE TITLE
missing product description in newly added genes in 3D7

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#17]
Genes that were newly added (and probably were not present when 3D7 was originally loaded into wikidata) are missing the product description:

Product: hypothetical protein
http://www.genedb.org/gene/PF3D7_1302050
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1302050

2 products: protein MGET and male gametocyte-enriched transcript 
http://www.genedb.org/gene/PF3D7_1469900
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1469900

**Comment by magnusmanske** [comment]
Product name will now be created correctly.
Your example PF3D7_1469900 has only one mRNA, so I only make one protein item.
https://www.genedb.org/#/gene/PF3D7_0105400 is an example for two proteins from one gene.

Fixed in code, will push out with next round of item updates
