### ISSUE TITLE
genes with alternative transcripts are missing GO terms and products

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#18]
There are currently 69 genes with alternative transcripts in 3D7. They are missing product description and GO terms. 

Here are two examples:
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1015200
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1147800

**Comment by magnusmanske** [comment]
These seem to be complete now, example: https://www.genedb.org/#/gene/PF3D7_1147800

**Comment by uliboehme** [comment]
Hi Magnus, 

There is still a problem with alternative transcripts. This examples has three transcripts. I can only see two on GeneDB. 
https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_1015200

You can see the three transcripts on PlasmoDB:
http://plasmodb.org/plasmo/app/record/gene/PF3D7_1015200#gene-structure
