### ISSUE TITLE
Alternative transcripts are listed as separate genes on chromosome list

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#19]
Alternative transcripts are listed as separate genes on chromosome list. This should be only one gene.

Here is an example:
https://tools.wmflabs.org/genedb/#/chromosome/Q18967854
PF3D7_1015200 is shown 4 times on the chromosome list. 
<img width="1122" alt="pf3d7_1015200" src="https://user-images.githubusercontent.com/25098772/50703102-f83ecb80-104a-11e9-88ee-a3382e5a72b7.png">

**Comment by magnusmanske** [comment]
Should be fixed: https://genedb.dev.sanger.ac.uk/#/chromosome/Pf3D7_10_v3
