### ISSUE TITLE
Missing products in newly loaded Plasmodium species

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#20]
A number of genes from recently loaded Plasmodium species are missing the product description. Here are a few examples:

![screen shot 2019-01-07 at 08 01 03](https://user-images.githubusercontent.com/25098772/50755908-699c9b00-1252-11e9-9c7e-cc1aa9e20952.png)
https://tools.wmflabs.org/genedb/#/gene/PKNH_1336700

![screen shot 2019-01-07 at 08 01 43](https://user-images.githubusercontent.com/25098772/50755935-7f11c500-1252-11e9-90ce-d7bd86c442c7.png)
https://tools.wmflabs.org/genedb/#/gene/PRCDC_0504000

![screen shot 2019-01-07 at 08 02 28](https://user-images.githubusercontent.com/25098772/50755974-994ba300-1252-11e9-805c-c2abc5b74eb7.png)
https://tools.wmflabs.org/genedb/#/gene/PVP01_1328100

![screen shot 2019-01-07 at 08 03 11](https://user-images.githubusercontent.com/25098772/50756002-af596380-1252-11e9-8325-dcd682772989.png)
https://tools.wmflabs.org/genedb/#/gene/PocGH01_13026900

**Comment by magnusmanske** [comment]
Fixed in code, will push out with next round of item updates
