### ISSUE TITLE
A few genes in 3D7 show a "+" in the product description

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#21]
Products in a few genes in 3D7 show a "+". This is not present in the  GFF file, GeneDB and PlasmoDB.
Here are a few examples:
![screen shot 2019-01-07 at 08 59 33](https://user-images.githubusercontent.com/25098772/50758706-d74cc500-125a-11e9-8a90-1f9beee66979.png)
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1447900

![screen shot 2019-01-07 at 09 05 41](https://user-images.githubusercontent.com/25098772/50758903-6bb72780-125b-11e9-898f-b63b10c350dc.png)
https://tools.wmflabs.org/genedb/#/gene/PF3D7_0831600

![screen shot 2019-01-07 at 09 08 04](https://user-images.githubusercontent.com/25098772/50759035-c2246600-125b-11e9-9e2b-4253e4e2d92b.png)
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1123100

**Comment by magnusmanske** [comment]
Appears to be fixed, example: https://www.genedb.org/#/gene/PF3D7_1447900
