### ISSUE TITLE
Dutch protein name is shown in general description

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#23]
The dutch description is shown in the general description on new GeneDB site. Here is an example:
https://www.wikidata.org/wiki/Q59923258
![screen shot 2019-01-26 at 16 25 45](https://user-images.githubusercontent.com/25098772/51790009-9116c180-2187-11e9-86e6-e08a04a8fd32.png)

This is how it looks on GeneDB. 
![screen shot 2019-01-26 at 16 25 59](https://user-images.githubusercontent.com/25098772/51790012-a7248200-2187-11e9-8414-4fd2c13e3041.png)

This is probably a little bit confusing for GeneDB users. Would be great if this could be removed.

**Comment by magnusmanske** [comment]
Fixed in dev branch with https://github.com/sanger-pathogens/GeneDB-static/commit/06797264ead4e3c1f00fa21b473c956ebdc4a554
