### ISSUE TITLE
Previously known as section shows current=false

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#24]
The Previously known as section includes current=false. This is an internal chado label and should not be included on gene pages. Would be great if this could be removed. 

Here are two examples:
https://tools.wmflabs.org/genedb/#/gene/PF3D7_0523000
https://tools.wmflabs.org/genedb/#/gene/PF3D7_0822600

**Comment by magnusmanske** [comment]
Fixed, items will be updated with next bot run.
Example: https://genedb.dev.sanger.ac.uk/#/gene/PF3D7_0523000
