### ISSUE TITLE
Links to MPMP, RMGM and Panoptes

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#25]
The curators of Malaria Parasite Metabolic Pathways (http://mpmp.huji.ac.il/) and RMgmDB (Rodent Malaria genetically modified Parasites) (https://www.pberghei.eu/index.php) would like to have links to their website on new GeneDB. Links are shown in the GFF file. Would be great if this could be added. 

There has also been a request quite some time ago to add Panoptes links on GeneDB. This was not possible on old GeneDB. Maybe there is an option to add this now.

**Comment by magnusmanske** [comment]
It looks like these are always the GeneDB IDs? If that's true, I can just add links to these sites without having to create/populate new Wikidata properties.

Are these suitable example URLs?
* http://mpmp.huji.ac.il/MapDetails/pfid?pfid=PF3D7_0513300
and 
* https://www.pberghei.eu/index.php?cat=geneid&q=PF3D7_1453800
? If not, please provide better ones!

**Comment by uliboehme** [comment]
There is a small difference in the MPMP link:
http://mpmp.huji.ac.il/pfid?pfid=PF3D7_0513300

MPMP links are present on all P. falciparum 3D7 genes. RMGM links are not present on all genes. The genes that have an RMGM link (mostly P. berghei genes) are shown in the GFF file.

**Comment by magnusmanske** [comment]
I have added both to the dev site now.

There is no straightforward way to add "is on RMGM" (there are convoluted ways) in Wikidata, so I'll just link every gene. If there is a pattern, let me know!

**Comment by uliboehme** [comment]
MPMP is a Plasmodium falciparum 3D7 specific database. Is it possible to only add those links to P. falciparum. They are currently on all Plasmodium species. Here is a P. berghei example:
https://genedb.dev.sanger.ac.uk/#/gene/PBANKA_1432300

As for RMGM, there is no pattern. This is phenotype database, mostly for rodent malaria genomes. They send us regularly a file listing genes that are present in their database. We load this file into chado. Ideally, it would be good to just add the link to genes that are in the GFF file.

**Comment by uliboehme** [comment]
Sorry, forgot to mention in my previous comment, that links to Panoptes would also be great. This was a request that we got quite a while back. It was not possible in old GeneDB, but maybe it is now a possibility.
