### ISSUE TITLE
Addition of EC numbers on the gene record page

### ISSUE THREAD

**Issue by uliboehme** [magnusmanske/genedb_wd#26]
Is there a possibility to include EC numbers on the gene page? 

Here are a few examples of genes with EC numbers:
https://tools.wmflabs.org/genedb/#/gene/PF3D7_1453800

https://tools.wmflabs.org/genedb/#/gene/PF3D7_0810800

**Comment by magnusmanske** [comment]
Just to make sure, that would be "EC enzyme number", resolving to enzyme.expasy.org ?

There are two parts to this:
* Adding EC numbers to Wikidata (from GFF or GAF, presumably)
* Displaying them in the web interface

Should they be added/displayed for the _gene_ or the _protein(s)_?

**Comment by uliboehme** [comment]
Thanks for looking into this! Yes, I meant enzyme numbers. It would be great to link to enzyme.expasy.org. This is also the link that PlasmoDB uses. Please see the following example:
http://plasmodb.org/plasmo/app/record/gene/PF3D7_1453800#function-analysis

If possible I would add it to the gene section in the same area as the other links (currently there are links to PlasmoDB, Apollo and Wikidata).

**Comment by magnusmanske** [comment]
Display in interface is now in dev branch.

TO-DO: Add to Wikidata from gff/gaf

**Comment by magnusmanske** [comment]
Done
